In [7]:
import pandas as pd

In [9]:
info = {
  "Name" : ["Bhavya", "Anya", "Chloe"],
  "GPA" : [4.7,3.4,2.5]
}

df = pd.DataFrame(info)
print(df)

     Name  GPA
0  Bhavya  4.7
1    Anya  3.4
2   Chloe  2.5

In [10]:
df

     Name  GPA
0  Bhavya  4.7
1    Anya  3.4
2   Chloe  2.5

In [16]:
s = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
print(s+s2)
print(s) # index and lael are different
type(s)
print(s[0]) # index based access

0    1
1    2
2    3
3    4
4    5
dtype: int64
1

In [33]:
s = pd.Series([24,25,26], index=["Bhavya", "Anya", "Chloe"])
print(s)
print(s["Bhavya"])
print(s["Anya"])

Bhavya    24
Anya      25
Chloe     26
dtype: int64
24
25

In [35]:
s = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
print(s+s2)
s[0] = 100
changed_s1 = s.drop(0)
print(s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [40]:
#data frames - 2D labelled columns are series 
info = {
  "Name" : ["Bhavya", "Anya", "Chloe"],
  "GPA" : [4.7,3.4,2.5],
    "Age" : [24,25,26]
}

df = pd.DataFrame(info)
print(df), type(df)
print(df.index)
print(df.columns)

     Name  GPA  Age
0  Bhavya  4.7   24
1    Anya  3.4   25
2   Chloe  2.5   26
RangeIndex(start=0, stop=3, step=1)

In [41]:
pd.DataFrame([["Anya", 9],["Bhavya", 18],["Michael", 19]], columns = ["Name", "Age"])

      Name  Age
0     Anya    9
1   Bhavya   18
2  Michael   19

In [42]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [6]:
# csv data
import pandas as pd
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [12]:
# json data
df = pd.read_json("store_data.json")
print(df, type(df))

       name rating                   feedback   age
0     Alice     5             Great product!!  25.0
1       Bob   four       ok but late Delivery  30.0
2   Charlie    two            BAD EXPERIENCE    NaN
3     Diana      5                  Loved it!  28.0
4       Eve    3.5  Average - could be better  20.0
5     Alice      5       Great product again!  25.0 <class 'pandas.core.frame.DataFrame'>

In [14]:
# csv data
import pandas as pd
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [16]:
#methods
print(df.head()) #prints initial five rows
df
print(df.tail(2)) #prints the last two rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [17]:
print(df.sample()) #prints a randomly generated row

   ID   Name  Age Department  Salary
6   7  Grace   41         HR   82000

In [23]:
df.info() #short summary about the data frame
df.shape #outputs a tuple of the row and column values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

(10, 5)

In [22]:
df.describe() #outputs the key statistics of the dataframe

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [30]:
df.nunique() #number of unique rows

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [29]:
df.columns #outputs the name of each column and the data type of the collective

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [5]:
#lets work with the AQI dataset
import pandas as pd
df = pd.read_csv("globalAirQuality.csv")
df.describe() #we import the data from the pandas and extract relevant stats
df["country"] #access to individual columns"
df[["city","aqi"]] #"

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [8]:
df.loc[2] #2nd row of data
df.loc[0:2] # furst 3 rows of data and loc is index inclusive

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [9]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [10]:
df.iloc[0:2] # start idx : end idx (exclusive)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [12]:
#access to indivudual columns -> df.loc(row, column)
df.loc[0, "aqi"]

np.int64(108)

In [21]:
df.loc[0:2, ["city","aqi", "latitude", "longitude"]]

       city  aqi  latitude  longitude
0  New York  108    40.713    -74.006
1  New York   90    40.713    -74.006
2  New York   84    40.713    -74.006

In [14]:
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [22]:
df.iloc[0:3, 1:5] # 2, 3 4 and 5 and iloc only takes numeric values

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [30]:
#scalar values//finding cells
df.at[0,"city"]
df.iat[0, 2]
cities = df["city"].copy()
cities[0] = "Mumbai "#view -> we're taking a slice but not a copy
cities

0         Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [31]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [43]:
#filtering of data
df[(df["aqi"]>100) & (df["temperature"] > 30)] #aqi's of greater than a 100 and a temp higher than 30
df[(df["aqi"]>100) & (df["temperature"] < 30)]

aqi_data = df[(df["aqi"]>100) & (df["temperature"] > 30)][["city","aqi"]] #chaning of conditions
aqi_data.iloc[0]
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

In [6]:
import pandas as pd
df = pd.read_csv("globalAirQuality.csv")
#second filtering method is just to use query methods // query = copy of data
df.query("aqi > 100 & temperature > 30")[["city","aqi"]]
aqi_val = 100
aqi_data = df.query("aqi > @aqi_val & temperature > 30")[["city","aqi"]].copy() #chained comparisons
aqi_data

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [8]:
""""""
data cleaning using pandas/using missing values:
isnull()/isna()
isnull().sum()
dropna()
fillna(value)
ffill()
bfill()
""""""

'\ndata cleaning using pandas/using missing values:\nisnull()/isna()\n'

In [13]:
#cleaning data using pandas
lf = pd.read_csv("raw_data.csv")
lf
#NaN -> automatically detected by pandas which is the missing values we need to clean

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [14]:
lf.isnull() #isna() gives the same output

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [16]:
lf.isnull().sum() #no of missing values per column

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [19]:
lf.dropna() #drops any rows with any empty cells 
lf.dropna(axis=1) #column drop

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [25]:
lf.fillna(0) # all missing cells will be filled with 0 or replace the missing ages with the mean age
age_mean = lf["age"].mean()
cleaned_data = lf.copy()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [28]:
#ffill() -> forward fill where we fill info from top to bottom in empty cells and bfill() -> backward fill()
lf.ffill()
lf.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [30]:
#handle dupes
lf["country"].duplicated()

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [32]:
lf2 = lf.copy()
lf.drop_duplicates(inplace=True)
lf = lf2

In [33]:
lf

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0